"""changed the client id data type on the role model from uuid to string

Revision ID: 30195e1647fb
Revises: f4dfa0568a27
Create Date: 2026-05-01 16:11:48.739476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '30195e1647fb'
down_revision: Union[str, Sequence[str], None] = 'f4dfa0568a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'client_id',
               existing_type=sa.CHAR(length=32),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'client_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
